include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: false
    always_use_package_imports: true
    directives_ordering: true
    sort_pub_dependencies: true

analyzer:
  errors:
    always_use_package_imports: error